<?xml version="1.0" encoding="UTF-8"?>
<bindings xmlns="http://java.sun.com/xml/ns/jaxb" version="2.1">

	<bindings xmlns:tns="urn:epcglobal:alelr:wsdl:1">

		<bindings scd="~tns:ALEException">
			<class ref="havis.middleware.ale.base.exception.ALEException" />
		</bindings>

		<bindings scd="~tns:DuplicateNameException">
			<class ref="havis.middleware.ale.base.exception.DuplicateNameException" />
		</bindings>


		<bindings scd="~tns:NoSuchNameException">
			<class ref="havis.middleware.ale.base.exception.NoSuchNameException" />
		</bindings>

		<bindings scd="~tns:InUseException">
			<class ref="havis.middleware.ale.base.exception.InUseException" />
		</bindings>

		<bindings scd="~tns:ValidationException">
			<class ref="havis.middleware.ale.base.exception.ValidationException" />
		</bindings>

		<bindings scd="~tns:ImmutableReaderException">
			<class ref="havis.middleware.ale.base.exception.ImmutableReaderException" />
		</bindings>

		<bindings scd="~tns:NonCompositeReaderException">
			<class ref="havis.middleware.ale.base.exception.NonCompositeReaderException" />
		</bindings>

		<bindings scd="~tns:ReaderLoopException">
			<class ref="havis.middleware.ale.base.exception.ReaderLoopException" />
		</bindings>

		<bindings scd="~tns:SecurityException">
			<class ref="havis.middleware.ale.base.exception.SecurityException" />
		</bindings>

		<bindings scd="~tns:ImplementationException">
			<class ref="havis.middleware.ale.base.exception.ImplementationException" />
		</bindings>

	</bindings>

</bindings>